humanized commands
rooom13/hot-tweets-bot pull request #71
Opened 2021-11-27 19:35 UTC by rangelrey

2021-11-28 09:58 UTC, rooom13 requested changes

2021-11-28 09:58 UTC, rooom13 commented on hot_tweets_bot/utils.py
> +    return regex_start + regex_body
1. delete lines 38 & 39 & chande 43 with:

`return f"\\w*(?i){regex_body}"`

2. add a docstring documenting what the function does +  what the regex is about
3. create_regex func name is too general, what kind of regex are you creating? Name shoudl be self explanatory
4. regex_piece is not self explanatory, what is that piece of regex doing?
5. in 41: a string is already a iterable, no need to convert it to list()

2021-11-28 09:58 UTC, rooom13 commented on hot_tweets_bot/app.py
> +                MessageHandler(Filters.regex(utils.create_regex("my searches")), self.callback_on_my_searches),
let's pass the command itself my_searches.

You can put it in a variable before the commandhandler & callback query handler: e.g:

command = "my_searches"
CommandHandler(command, self.callback_on_my_searches),
CallbackQueryHandler(self.callback_on_my_searches, pattern=fr"\/{command"),
                MessageHandler(Filters.regex(utils.create_regex("command"))

2021-11-28 09:58 UTC, rooom13 commented on tests/test_utils.py
> +def test_create_regex():
this test testes the function but not the regex

Please make use of a @pytest.mark.parametrize decorator for testing all test cases

2021-11-29 16:25 UTC, rooom13 requested changes

2021-11-29 16:25 UTC, rooom13 commented on hot_tweets_bot/app.py
> +command_admin = "admin"
pls put this in a class so they are not just global variables

```
class Commands:
    add_search = "..."
    ...
```

2021-11-29 16:25 UTC, rooom13 commented on hot_tweets_bot/utils.py
> +def create_regex_contains_characters(input):
please add type hints, i.e.: `def create_regex_contains_characters(input: str) -> str:`

2021-11-29 16:25 UTC, rooom13 commented on tests/test_utils.py
> +def test_create_regex_contains_characters():
1. consider using `@pytest.mark.parametrize` ->check this article: https://docs.pytest.org/en/6.2.x/example/parametrize.html#different-options-for-test-ids  You can as well find some examples within the code

2. you are testing the regex creation but not the regex itself. Please test it so we are sure the regex works as expected

2021-12-04 13:45 UTC, rooom13 requested changes

2021-12-04 13:45 UTC, rooom13 commented on hot_tweets_bot/app.py
> +                MessageHandler(Filters.regex(utils.create_regex_contains_characters(f"/{Commands.start}")), self.callback_on_start),
porqué a la regex se le pasa /start y no directamente start? Mejor pasarle start directamente

2021-12-04 13:45 UTC, rooom13 commented on hot_tweets_bot/utils.py
> +    regex_ignore_split_characters = "x(\\s*|x*|_*|-*)"
```
a = "pepe{char}"
a.format(char="churra") 
>>> "pepechurra"

```

2021-12-04 13:45 UTC, rooom13 commented on hot_tweets_bot/utils.py
> +    regex_body = ""
you can as well first define all chars to remove

```
rem_chars = "_- /"
for c in rem_chars
    input = input.replace(c, "")
```

In this way you can maybe generate the var `regex_ignore_split_characters` based on rem_chars

2021-12-04 13:45 UTC, rooom13 commented on tests/test_utils.py
> +    assert result == expected
nice usage of test parametrization.

2021-12-04 14:31 UTC, rooom13 requested changes

2021-12-04 14:31 UTC, rooom13 commented on hot_tweets_bot/app.py
> +                MessageHandler(Filters.regex(utils.create_regex_contains_characters(Commands.delete_searc)), self.callback_inline_delete_search),
What is this `Commands.delete_searc`, `Commands.my_searche)`

2021-12-04 14:31 UTC, rooom13 commented on hot_tweets_bot/app.py
> +                    CallbackQueryHandler(self.callback_on_stop_feedback, pattern=rf"\/{Commands.stop_feedback} .*"),
porque aqui neceitamos "\/" and in line 288 no need for it?

2021-12-04 14:31 UTC, rooom13 commented on hot_tweets_bot/app.py
> +                CallbackQueryHandler(self.callback_on_cancel, pattern=rf"\/{Commands.cancel}"),
same here, why \/ is needed here and not in line 388

2021-12-04 14:44 UTC, rangelrey commented on hot_tweets_bot/app.py
> +                CallbackQueryHandler(self.callback_on_cancel, pattern=rf"\/{Commands.cancel}"),
typo

2021-12-04 14:45 UTC, rangelrey commented on hot_tweets_bot/app.py
> +                CallbackQueryHandler(self.callback_on_cancel, pattern=rf"\/{Commands.cancel}"),
typo in the previous one

2021-12-04 14:46 UTC, rooom13 approved these changes

2021-12-04 14:46 UTC, merged